# Generated by Django 5.0.3 on 2024-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('mastercategory', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('articletype', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
    ]
